# Generated by Django 5.2.11 on 2026-02-18 20:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0001_initial"),
        ("companies", "0002_initial"),
        ("contacts", "0001_initial"),
        ("journals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bill_no", models.BigIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("posted", "Posted"),
                            ("partially_paid", "Partially Paid"),
                            ("paid", "Paid"),
                            ("void", "Void"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("bill_date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                ("currency_code", models.CharField(default="USD", max_length=3)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "tax_total",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "ap_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="ap_bills",
                        to="accounting.account",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bills",
                        to="companies.company",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bills",
                        to="journals.journalentry",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="bills",
                        to="contacts.contact",
                    ),
                ),
            ],
            options={
                "db_table": "bill",
                "ordering": ["-bill_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BillLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("line_no", models.PositiveIntegerField()),
                ("description", models.TextField()),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, default=1, max_digits=19),
                ),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "line_total",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="purchases.bill",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bill_lines",
                        to="companies.company",
                    ),
                ),
                (
                    "expense_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="bill_lines",
                        to="accounting.account",
                    ),
                ),
            ],
            options={
                "db_table": "bill_line",
            },
        ),
        migrations.CreateModel(
            name="VendorPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("payment_no", models.BigIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("posted", "Posted"),
                            ("void", "Void"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("paid_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=4, max_digits=19)),
                ("currency_code", models.CharField(default="USD", max_length=3)),
                ("notes", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_payments",
                        to="companies.company",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendor_payments",
                        to="journals.journalentry",
                    ),
                ),
                (
                    "payment_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="vendor_payments",
                        to="accounting.account",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="vendor_payments",
                        to="contacts.contact",
                    ),
                ),
            ],
            options={
                "db_table": "vendor_payment",
                "ordering": ["-paid_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VendorPaymentAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=4, max_digits=19)),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="vendor_payment_allocations",
                        to="purchases.bill",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_payment_allocations",
                        to="companies.company",
                    ),
                ),
                (
                    "vendor_payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="purchases.vendorpayment",
                    ),
                ),
            ],
            options={
                "db_table": "vendor_payment_allocation",
            },
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["company", "status"], name="bill_company_607e80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["company", "vendor"], name="bill_company_29a6be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["company", "bill_date"], name="bill_company_710a6a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bill",
            unique_together={("company", "bill_no")},
        ),
        migrations.AddIndex(
            model_name="billline",
            index=models.Index(fields=["bill"], name="bill_line_bill_id_d1ea49_idx"),
        ),
        migrations.AddConstraint(
            model_name="billline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="bill_line_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="billline",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_cost__gte", 0)),
                name="bill_line_unit_cost_non_negative",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="billline",
            unique_together={("company", "bill", "line_no")},
        ),
        migrations.AddIndex(
            model_name="vendorpayment",
            index=models.Index(
                fields=["company", "paid_date"], name="vendor_paym_company_e64b5c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vendorpayment",
            unique_together={("company", "payment_no")},
        ),
        migrations.AddIndex(
            model_name="vendorpaymentallocation",
            index=models.Index(
                fields=["vendor_payment"], name="vendor_paym_vendor__dc7545_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="vendorpaymentallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="vendor_payment_allocation_amount_positive",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vendorpaymentallocation",
            unique_together={("company", "vendor_payment", "bill")},
        ),
    ]
