"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_env_file(path: Path) -> None:
    if not path.exists():
        return

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        if not key or os.getenv(key) is not None:
            continue
        os.environ[key] = value.strip().strip('"').strip("'")


load_env_file(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-+r9+^i0$s*)muc+*ik67=hgob4b*l(ifpo6mqt^7$w9k#x==k^")

# SECURITY WARNING: don't run with debug turned on in production!


def env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_int(name: str, default: int) -> int:
    value = os.getenv(name)
    if value is None:
        return default
    try:
        return int(value)
    except ValueError:
        return default


def env_list(name: str, default: list[str] | None = None) -> list[str]:
    value = os.getenv(name)
    if value is None:
        return list(default or [])
    return [item.strip().lower() for item in value.split(",") if item.strip()]


DEBUG = env_bool("DEBUG", True)
ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", default=["127.0.0.1", "localhost", ".vercel.app"])


def database_from_url(url: str) -> dict:
    parsed = urlparse(url)
    scheme = parsed.scheme.lower()

    if scheme in {"postgres", "postgresql"}:
        query = parse_qs(parsed.query, keep_blank_values=True)
        options = {key: values[-1] for key, values in query.items() if values and values[-1] != ""}

        config = {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": unquote(parsed.path.lstrip("/")) or "postgres",
            "USER": unquote(parsed.username or ""),
            "PASSWORD": unquote(parsed.password or ""),
            "HOST": parsed.hostname or "127.0.0.1",
            "PORT": int(parsed.port or 5432),
            "CONN_MAX_AGE": env_int("POSTGRES_CONN_MAX_AGE", 60),
        }
        if options:
            config["OPTIONS"] = options
        return config

    if scheme == "sqlite":
        db_name = unquote(parsed.path.lstrip("/")) or ":memory:"
        if parsed.path == "/:memory:":
            db_name = ":memory:"
        return {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": db_name,
        }

    raise ValueError(f"Unsupported DATABASE_URL scheme: {parsed.scheme}")


ENABLE_BROWSABLE_API = env_bool("ENABLE_BROWSABLE_API", DEBUG)
SYSTEM_ADMIN_ENABLED = env_bool("SYSTEM_ADMIN_ENABLED", False)
AI_ENABLED = env_bool("AI_ENABLED", False)
SUBSCRIPTION_ENABLED = env_bool("SUBSCRIPTION_ENABLED", False)
PROTECTED_SYSTEM_USER_EMAILS = env_list("PROTECTED_SYSTEM_USER_EMAILS", default=[])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "drf_spectacular",
    "django_filters",
    "apps.common",
    "apps.users",
    "apps.companies",
    "apps.rbac",
    "apps.accounting",
    "apps.journals",
    "apps.contacts",
    "apps.sales",
    "apps.purchases",
    "apps.banking",
    "apps.reports",
    "apps.documents",
    "apps.audit",
    "apps.idempotency",
    "apps.system_admin",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "apps.common.middleware.RequestIDMiddleware",
    "apps.common.middleware.ErrorEnvelopeMiddleware",
    "apps.system_admin.middleware.SystemAdminErrorAuditMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

USE_SQLITE = env_bool("USE_SQLITE", False)
DATABASE_URL = os.getenv("DATABASE_URL", "").strip()

if DATABASE_URL:
    DATABASES = {
        "default": database_from_url(DATABASE_URL),
    }
elif USE_SQLITE:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB", "uraccount"),
            "USER": os.getenv("POSTGRES_USER", "uraccount"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD", "uraccount"),
            "HOST": os.getenv("POSTGRES_HOST", "127.0.0.1"),
            "PORT": env_int("POSTGRES_PORT", 5432),
            "CONN_MAX_AGE": env_int("POSTGRES_CONN_MAX_AGE", 60),
        }
    }

    postgres_sslmode = os.getenv("POSTGRES_SSLMODE", "").strip()
    if postgres_sslmode:
        DATABASES["default"]["OPTIONS"] = {"sslmode": postgres_sslmode}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "apps.users.authentication.PasswordVersionJWTAuthentication",
    ),
    "DEFAULT_PAGINATION_CLASS": "apps.common.pagination.DefaultListPagination",
    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
    ),
    "EXCEPTION_HANDLER": "apps.common.exceptions.standardized_exception_handler",
    "DEFAULT_THROTTLE_CLASSES": (
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.ScopedRateThrottle",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "user": "120/min",
        "anon": "60/min",
        "auth_login": "10/min",
        "system_password_reset": "20/min",
        "system_role_mutation": "60/min",
    },
}

SIMPLE_JWT = {
    "TOKEN_OBTAIN_SERIALIZER": "apps.users.serializers_jwt.PasswordVersionTokenObtainPairSerializer",
}

if ENABLE_BROWSABLE_API:
    REST_FRAMEWORK["DEFAULT_AUTHENTICATION_CLASSES"] += (
        "rest_framework.authentication.SessionAuthentication",
    )
    REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"] += (
        "rest_framework.renderers.BrowsableAPIRenderer",
    )

SPECTACULAR_SETTINGS = {
    "TITLE": "URAccount API",
    "DESCRIPTION": "URAccount backend API",
    "VERSION": "0.1.0",
}

CORS_ALLOWED_ORIGINS = env_list(
    "CORS_ALLOWED_ORIGINS",
    default=[
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ],
)

AUTH_USER_MODEL = "users.User"

# Prevent default Django auth redirect to /accounts/profile/
LOGIN_REDIRECT_URL = "/api/v1/docs/"
LOGOUT_REDIRECT_URL = "/api-auth/login/"

LOG_LEVEL = os.getenv("DJANGO_LOG_LEVEL", "INFO")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "request_id": {
            "()": "apps.common.logging.RequestIDLogFilter",
        },
    },
    "formatters": {
        "standard": {
            "format": "%(asctime)s %(levelname)s [%(name)s] [request_id=%(request_id)s] %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "filters": ["request_id"],
            "formatter": "standard",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django.server": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
