ROLE_OWNER = "Owner"
ROLE_ADMIN = "Admin"
ROLE_ACCOUNTANT = "Accountant"
ROLE_VIEWER = "Viewer"

PERMISSION_COMPANY_MANAGE = "company.manage"
PERMISSION_MEMBERS_MANAGE = "members.manage"
PERMISSION_RBAC_MANAGE = "rbac.manage"
PERMISSION_ACCOUNTING_VIEW = "accounting.view"
PERMISSION_ACCOUNTING_POST = "accounting.post"

DEFAULT_ROLE_PERMISSIONS = {
    ROLE_OWNER: {
        PERMISSION_COMPANY_MANAGE,
        PERMISSION_MEMBERS_MANAGE,
        PERMISSION_RBAC_MANAGE,
        PERMISSION_ACCOUNTING_VIEW,
        PERMISSION_ACCOUNTING_POST,
    },
    ROLE_ADMIN: {
        PERMISSION_COMPANY_MANAGE,
        PERMISSION_MEMBERS_MANAGE,
        PERMISSION_ACCOUNTING_VIEW,
        PERMISSION_ACCOUNTING_POST,
    },
    ROLE_ACCOUNTANT: {
        PERMISSION_ACCOUNTING_VIEW,
        PERMISSION_ACCOUNTING_POST,
    },
    ROLE_VIEWER: {
        PERMISSION_ACCOUNTING_VIEW,
    },
}
