# Generated by Django 5.2.11 on 2026-02-19 13:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_initial"),
        ("system_admin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemCompanyConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ai_enabled", models.BooleanField(default=False)),
                ("ai_suggestions_enabled", models.BooleanField(default=False)),
                ("ai_rag_enabled", models.BooleanField(default=False)),
                ("max_users", models.PositiveIntegerField(blank=True, null=True)),
                ("max_storage_mb", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "max_api_requests_per_minute",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("extra_flags", models.JSONField(blank=True, default=dict)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_config",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Company Config",
                "verbose_name_plural": "System Company Configs",
                "db_table": "system_company_config",
            },
        ),
    ]
