# Generated by Django 5.2.11 on 2026-02-18 20:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("vendor", "Vendor"),
                            ("both", "Both"),
                        ],
                        default="both",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=64)),
                ("address", models.TextField(blank=True)),
                ("tax_id", models.CharField(blank=True, max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "contact",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["company", "type"], name="contact_company_d4b571_idx"
                    )
                ],
            },
        ),
    ]
