# Generated by Django 5.2.11 on 2026-02-18 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rbac", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="companyroleassignment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="companyrolepermission",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_permissions",
                to="rbac.companyrole",
            ),
        ),
        migrations.AddField(
            model_name="companyrolepermission",
            name="permission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="role_permissions",
                to="rbac.permission",
            ),
        ),
        migrations.AddIndex(
            model_name="companyrole",
            index=models.Index(
                fields=["company", "name"], name="company_rol_company_8997cb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="companyrole",
            unique_together={("company", "name")},
        ),
        migrations.AddIndex(
            model_name="companyroleassignment",
            index=models.Index(
                fields=["company", "user"], name="company_rol_company_71b818_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="companyroleassignment",
            unique_together={("company", "user", "role")},
        ),
        migrations.AlterUniqueTogether(
            name="companyrolepermission",
            unique_together={("role", "permission")},
        ),
    ]
