# Generated by Django 5.2.11 on 2026-02-18 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinvitation",
            name="invited_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_company_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="companymember",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="companymember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="companyinvitation",
            index=models.Index(
                fields=["company"], name="company_inv_company_a8eb0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companyinvitation",
            index=models.Index(fields=["token"], name="company_inv_token_f91fa6_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="companyinvitation",
            unique_together={("company", "email")},
        ),
        migrations.AddIndex(
            model_name="companymember",
            index=models.Index(
                fields=["company"], name="company_mem_company_470bba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companymember",
            index=models.Index(fields=["user"], name="company_mem_user_id_53fa97_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="companymember",
            unique_together={("company", "user")},
        ),
    ]
