import type { LucideIcon } from "lucide-react";
import {
  BadgeDollarSign,
  BookOpen,
  BookText,
  Building2,
  ChartNoAxesCombined,
  CircleCheckBig,
  ClipboardCheck,
  ClockAlert,
  Equal,
  Eye,
  FileArchive,
  FileSpreadsheet,
  FileText,
  GitCompareArrows,
  Globe,
  GraduationCap,
  HandCoins,
  HeartPulse,
  Hourglass,
  Landmark,
  LaptopMinimalCheck,
  LibraryBig,
  Link2,
  ListChecks,
  Lock,
  Mail,
  MessageCircle,
  Microscope,
  NotebookPen,
  Palmtree,
  Phone,
  PlaneTakeoff,
  Printer,
  ReceiptText,
  Rows4,
  Scale,
  Shield,
  ShieldCheck,
  Sprout,
  Stamp,
  Target,
  TrendingUp,
  TriangleAlert,
  Upload,
  Users,
  Wallet,
  Zap,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  BadgeDollarSign,
  BookOpen,
  BookText,
  Building2,
  ChartNoAxesCombined,
  CircleCheckBig,
  ClipboardCheck,
  ClockAlert,
  Equal,
  Eye,
  FileArchive,
  FileSpreadsheet,
  FileText,
  GitCompareArrows,
  Globe,
  GraduationCap,
  HandCoins,
  HeartPulse,
  Hourglass,
  Landmark,
  LaptopMinimalCheck,
  LibraryBig,
  Link2,
  ListChecks,
  Lock,
  Mail,
  MessageCircle,
  Microscope,
  NotebookPen,
  Palmtree,
  Phone,
  PlaneTakeoff,
  Printer,
  ReceiptText,
  Rows4,
  Scale,
  Shield,
  ShieldCheck,
  Sprout,
  Stamp,
  Target,
  TrendingUp,
  TriangleAlert,
  Upload,
  Users,
  Wallet,
  Zap,
};

type PublicIconProps = {
  name: string;
  className?: string;
};

export function PublicIcon({ name, className }: PublicIconProps) {
  const Icon = iconMap[name] ?? BookOpen;
  return <Icon className={className} />;
}

