# Generated by Django 5.2.11 on 2026-02-18 18:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scope", models.CharField(max_length=120)),
                ("idempotency_key", models.CharField(max_length=255)),
                ("request_hash", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("in_progress", "In Progress"),
                            ("failed", "Failed"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                ("response_body", models.JSONField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idempotency_records",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "idempotency_record",
                "indexes": [
                    models.Index(
                        fields=["company", "scope"],
                        name="idempotency_company_ba8e18_idx",
                    )
                ],
                "unique_together": {("company", "scope", "idempotency_key")},
            },
        ),
    ]
