# Generated by Django 5.2.11 on 2026-02-18 20:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0001_initial"),
        ("companies", "0002_initial"),
        ("contacts", "0001_initial"),
        ("journals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("invoice_no", models.BigIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("posted", "Posted"),
                            ("partially_paid", "Partially Paid"),
                            ("paid", "Paid"),
                            ("void", "Void"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("issue_date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                ("currency_code", models.CharField(default="USD", max_length=3)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "tax_total",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "ar_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="ar_invoices",
                        to="accounting.account",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="companies.company",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="invoices",
                        to="contacts.contact",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="journals.journalentry",
                    ),
                ),
            ],
            options={
                "db_table": "invoice",
                "ordering": ["-issue_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("line_no", models.PositiveIntegerField()),
                ("description", models.TextField()),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, default=1, max_digits=19),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "line_total",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_lines",
                        to="companies.company",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sales.invoice",
                    ),
                ),
                (
                    "revenue_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="invoice_lines",
                        to="accounting.account",
                    ),
                ),
            ],
            options={
                "db_table": "invoice_line",
            },
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("receipt_no", models.BigIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("posted", "Posted"),
                            ("void", "Void"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("received_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=4, max_digits=19)),
                ("currency_code", models.CharField(default="USD", max_length=3)),
                ("notes", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="companies.company",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="receipts",
                        to="contacts.contact",
                    ),
                ),
                (
                    "deposit_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="receipts",
                        to="accounting.account",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receipts",
                        to="journals.journalentry",
                    ),
                ),
            ],
            options={
                "db_table": "receipt",
                "ordering": ["-received_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReceiptAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=4, max_digits=19)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt_allocations",
                        to="companies.company",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="receipt_allocations",
                        to="sales.invoice",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="sales.receipt",
                    ),
                ),
            ],
            options={
                "db_table": "receipt_allocation",
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["company", "status"], name="invoice_company_5eccef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["company", "customer"], name="invoice_company_766fce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["company", "issue_date"], name="invoice_company_c7afd1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="invoice",
            unique_together={("company", "invoice_no")},
        ),
        migrations.AddIndex(
            model_name="invoiceline",
            index=models.Index(
                fields=["invoice"], name="invoice_lin_invoice_01676d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="invoice_line_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceline",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", 0)),
                name="invoice_line_unit_price_non_negative",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="invoiceline",
            unique_together={("company", "invoice", "line_no")},
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["company", "received_date"], name="receipt_company_cf064a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="receipt",
            unique_together={("company", "receipt_no")},
        ),
        migrations.AddIndex(
            model_name="receiptallocation",
            index=models.Index(
                fields=["receipt"], name="receipt_all_receipt_efe3d4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="receiptallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="receipt_allocation_amount_positive",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="receiptallocation",
            unique_together={("company", "receipt", "invoice")},
        ),
    ]
