# Generated by Django 5.2.11 on 2026-02-18 21:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0001_initial"),
        ("companies", "0002_initial"),
        ("journals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("account_number_last4", models.CharField(blank=True, max_length=4)),
                ("currency_code", models.CharField(default="USD", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to="companies.company",
                    ),
                ),
                (
                    "ledger_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="bank_accounts",
                        to="accounting.account",
                    ),
                ),
            ],
            options={
                "db_table": "bank_account",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BankReconciliation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "closing_balance",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("finalized", "Finalized")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliations",
                        to="banking.bankaccount",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_reconciliations",
                        to="companies.company",
                    ),
                ),
                (
                    "finalized_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finalized_bank_reconciliations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bank_reconciliation",
                "ordering": ["-end_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BankStatementImport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("parsed", "Parsed"),
                            ("failed", "Failed"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("raw_content", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imports",
                        to="banking.bankaccount",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_statement_imports",
                        to="companies.company",
                    ),
                ),
                (
                    "imported_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_statement_imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bank_statement_import",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BankTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("txn_date", models.DateField()),
                ("description", models.TextField(blank=True)),
                ("reference", models.CharField(blank=True, max_length=128)),
                ("amount", models.DecimalField(decimal_places=4, max_digits=19)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("imported", "Imported"),
                            ("matched", "Matched"),
                            ("reconciled", "Reconciled"),
                            ("ignored", "Ignored"),
                        ],
                        default="imported",
                        max_length=20,
                    ),
                ),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="banking.bankaccount",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_transactions",
                        to="companies.company",
                    ),
                ),
                (
                    "matched_journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_transactions",
                        to="journals.journalentry",
                    ),
                ),
                (
                    "statement_import",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="banking.bankstatementimport",
                    ),
                ),
            ],
            options={
                "db_table": "bank_transaction",
                "ordering": ["-txn_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BankReconciliationLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_reconciliation_lines",
                        to="companies.company",
                    ),
                ),
                (
                    "reconciliation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="banking.bankreconciliation",
                    ),
                ),
                (
                    "bank_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="reconciliation_lines",
                        to="banking.banktransaction",
                    ),
                ),
            ],
            options={
                "db_table": "bank_reconciliation_line",
            },
        ),
        migrations.AddIndex(
            model_name="bankaccount",
            index=models.Index(
                fields=["company", "is_active"], name="bank_accoun_company_e000bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bankreconciliation",
            index=models.Index(
                fields=["company", "status"], name="bank_reconc_company_9b0720_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bankreconciliation",
            index=models.Index(
                fields=["company", "bank_account"],
                name="bank_reconc_company_214ceb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bankstatementimport",
            index=models.Index(
                fields=["company", "status"], name="bank_statem_company_61e196_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="banktransaction",
            index=models.Index(
                fields=["company", "status"], name="bank_transa_company_688ffd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="banktransaction",
            index=models.Index(
                fields=["company", "txn_date"], name="bank_transa_company_a5fced_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="banktransaction",
            index=models.Index(
                fields=["company", "bank_account"],
                name="bank_transa_company_39a3b5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bankreconciliationline",
            index=models.Index(
                fields=["reconciliation"], name="bank_reconc_reconci_f4d62c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bankreconciliationline",
            unique_together={("company", "reconciliation", "bank_transaction")},
        ),
    ]
